Repository masters2023-project-team05-second-hand/second-hand-max-fe, pull requests merged in 2023-08, with the labels that each got.

#3 디자인 시스템 설정
  index.html
  src/App.tsx
  src/assets/icon/camera.svg
  src/assets/icon/check.svg
  src/assets/icon/chevron-down.svg
  src/assets/icon/chevron-left.svg
  src/assets/icon/chevron-right.svg
  src/assets/icon/chevron-up.svg
  src/assets/icon/circle-x-filled.svg
  src/assets/icon/dots.svg
  src/assets/icon/exclamation-circle.svg
  src/assets/icon/heart-filled.svg
  src/assets/icon/heart.svg
  src/assets/icon/home.svg
  src/assets/icon/layout-grid.svg
  src/assets/icon/map-pin-filled.svg
  src/assets/icon/message-noti.svg
  src/assets/icon/message.svg
  src/assets/icon/news.svg
  src/assets/icon/paperclip.svg
  src/assets/icon/pencil.svg
  src/assets/icon/photo.svg
  src/assets/icon/plus.svg
  src/assets/icon/search.svg
  src/assets/icon/send.svg
  src/assets/icon/user-circle.svg
  src/assets/icon/x.svg
  src/assets/react.svg
  src/styles/GlobalStyle.tsx
  src/styles/designSystem.ts
Labels: ui

#9 [UI] Button Component 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/Button.tsx
  src/styles/designSystem.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: ui

#11 [Chore] Styled DefaultTheme type 설정
  src/App.tsx
  src/styles/designSystem.ts
  src/styles/styled.d.ts
Labels: chore

#10 [UI] Menu Component 구현
  src/components/common/Menu/Menu.tsx
  src/components/common/Menu/MenuIndicator.tsx
  src/components/common/Menu/MenuItem.tsx
  src/hooks/useDropdown.ts
  src/styles/GlobalStyle.tsx
Labels: ui

#12 [UI] Modal 공용 컴포넌트, AddressModal, CategoryModal UI 구현
  src/App.tsx
  src/components/Modal/AddressModal/AddressModal.tsx
  src/components/Modal/AddressModal/Content/AddressIndicatorList.tsx
  src/components/Modal/AddressModal/Content/AddressSearch.tsx
  src/components/Modal/CategoryModal/CategoryModal.tsx
  src/components/Modal/CategoryModal/CategoryModalContent.tsx
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalHeader.tsx
  src/customTypes/index.ts
  src/mocks/data/address.ts
  src/mocks/data/categories.ts
Labels: ui

#13 [UI] Alert Component 구현
  src/components/common/Alert/Alert.tsx
Labels: ui

#14 [Refactor] 버튼 컴포넌트 props, designSystem filter type error 수정
  src/components/Modal/AddressModal/Content/AddressIndicatorList.tsx
  src/components/common/Button.tsx
  src/styles/designSystem.ts
Labels: refactor

#15 [refactor] 1주차 마스터 피드백 반영
  src/components/common/Menu/MenuIndicator.tsx
  src/components/common/Menu/MenuItem.tsx
  src/hooks/useDropdown.ts
Labels: refactor

#20 [FE] 기본 Router 설정, 상태관리 라이브러리 추가
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/Chat.tsx
  src/pages/Home/Category.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/NewProduct.tsx
  src/pages/MyAccount.tsx
  src/pages/Product.tsx
  src/pages/SalesList.tsx
  src/pages/WishList.tsx
Labels: feat

#26 Storybook 설치 및 기본 설정
  .eslintrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/stories/Button.stories.tsx
  src/stories/Modal.stories.tsx
  src/stories/NavigationBar.stories.tsx
  src/stories/example/Button.stories.ts
  src/stories/example/Button.tsx
  src/stories/example/Header.stories.ts
  src/stories/example/Header.tsx
  src/stories/example/Page.stories.ts
  src/stories/example/Page.tsx
  src/stories/example/button.css
  src/stories/example/header.css
  src/stories/example/page.css
  yarn.lock
Labels: chore, test

#25 NavigationBar 컴포넌트
  src/App.tsx
  src/components/NavigationBar.tsx
  src/components/common/Button.tsx
  src/constants/path.ts
  src/main.tsx
  src/pages/Chat.tsx
  src/pages/Home/Home.tsx
  src/pages/MyAccount.tsx
  src/pages/SalesList.tsx
  src/pages/WishList.tsx
Labels: feat, ui

#28 NavigationBar key 위치 수정
  src/components/NavigationBar.tsx
Labels: fix

#27 TopBar 컴포넌트
  src/components/NavigationBar.tsx
  src/components/TopBar.tsx
  src/components/common/Menu/Menu.tsx
  src/components/common/Menu/MenuIndicator.tsx
  src/components/common/Menu/MenuItem.tsx
  src/hooks/useScroll.ts
  src/pages/Chat.tsx
  src/pages/Home/Category.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/NewProduct.tsx
  src/pages/MyAccount.tsx
  src/pages/Product.tsx
  src/pages/SalesList.tsx
  src/pages/WishList.tsx
  src/styles/designSystem.ts
Labels: feat, ui

#29 Menu, Alert 리팩토링
  package-lock.json
  src/App.tsx
  src/components/TopBar.tsx
  src/components/common/Alert/Alert.tsx
  src/components/common/Alert/AlertIndicator.tsx
  src/components/common/Menu/Menu.tsx
  src/components/common/Menu/MenuIndicator.tsx
  src/components/common/Menu/MenuItem.tsx
  src/constants/path.ts
  src/customTypes/index.ts
  src/hooks/useDropdown.ts
  src/hooks/useOutsideClick.ts
  src/pages/Test.tsx
  src/styles/designSystem.ts
  yarn.lock
Labels: feat, chore, refactor

#30 소셜 로그인 버튼 및 로그인 UI 구현
  .gitignore
  .vscode/settings.json
  src/App.tsx
  src/assets/icon/github.svg
  src/assets/image/gaji.png
  src/assets/image/kakao.png
  src/components/Intro.tsx
  src/components/Login.tsx
  src/components/Modal/AddressModal/Content/AddressIndicatorList.tsx
  src/components/Modal/ModalHeader.tsx
  src/components/NavigationBar.tsx
  src/components/TopBar.tsx
  src/components/common/Alert/Alert.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Buttons/SocialButtons.tsx
  src/components/common/Buttons/type.ts
  src/pages/Home/Category.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/NewProduct.tsx
  src/pages/MyAccount.tsx
  src/pages/Product.tsx
  src/pages/Test.tsx
  src/stories/Button.stories.tsx
  src/styles/common.ts
  src/styles/constants.ts
  src/styles/designSystem.ts
Labels: ui

#31 프로젝트 전체 UI 작업
  src/App.tsx
  src/components/NavigationBar.tsx
  src/pages/Chat.tsx
  src/pages/Home/Category.tsx
  src/pages/Home/NewProduct.tsx
  src/pages/MyAccount.tsx
  src/pages/Product.tsx
  src/pages/SalesList.tsx
  src/pages/Test.tsx
  src/pages/WishList.tsx
  src/styles/GlobalStyle.tsx
  src/styles/common.ts
Labels: ui

#32 타입, 상수 의미단위로 관리
  src/App.tsx
  src/components/NavigationBar.tsx
  src/components/common/Menu/Menu.tsx
  src/components/common/Menu/MenuIndicator.tsx
  src/components/common/Menu/MenuItem.tsx
  src/components/common/Menu/type.ts
  src/customTypes/index.ts
  src/hooks/useOutsideClick.ts
  src/pages/Test.tsx
  src/router/constant.ts
  src/router/router.tsx
  tsconfig.json
Labels: chore, refactor

#37 MyAccount Page 주요 컴포넌트 구성 및 UI 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/constants.ts
  src/api/fetcher.ts
  src/api/index.ts
  src/api/type.ts
  src/assets/image/loading.gif
  src/components/Intro.tsx
  src/components/Modal/AddressModal/AddressModal.tsx
  src/components/Modal/AddressModal/Content/AddressIndicatorList.tsx
  src/components/Modal/Modal.tsx
  src/components/NavigationBar.tsx
  src/components/ProfileUploadButton.tsx
  src/components/UserAccount.tsx
  src/customTypes/index.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/data/address.ts
  src/mocks/handlers.ts
  src/pages/MyAccount.tsx
  src/pages/MyAccount/Auth.tsx
  src/pages/MyAccount/Login.tsx
  src/pages/MyAccount/MyAccount.tsx
  src/pages/MyAccount/Register.tsx
  src/pages/MyAccount/Setting.tsx
  src/router/constant.ts
  src/router/constants.ts
  src/router/router.tsx
  src/store/index.ts
  src/styles/common.ts
  yarn.lock
Labels: feat

#38 깃허브 OAuth 로그인 기능 구현
  src/api/constants.ts
  src/mocks/handlers.ts
  src/pages/MyAccount/Login.tsx
Labels: feat
