Repository masters2023-project-team05-second-hand/second-hand-max-fe, pull requests merged in 2023-09, with the labels that each got.

#39 상태 관리 개선 & 유저 정보 설정
  src/App.tsx
  src/api/constants.ts
  src/api/fetcher.ts
  src/api/index.ts
  src/api/type.ts
  src/components/Modal/AddressModal/AddressModal.tsx
  src/components/Modal/AddressModal/Content/AddressIndicatorList.tsx
  src/components/Modal/AddressModal/Content/AddressSearch.tsx
  src/components/Modal/CategoryModal/CategoryModal.tsx
  src/components/Modal/CategoryModal/CategoryModalContent.tsx
  src/components/Modal/Modal.tsx
  src/components/NavigationBar.tsx
  src/components/ProfileUploadButton.tsx
  src/components/TopBar.tsx
  src/components/UserAccount.tsx
  src/components/common/Alert/Alert.tsx
  src/mocks/handlers.ts
  src/pages/Auth.tsx
  src/pages/MyAccount/Auth.tsx
  src/pages/MyAccount/MyAccount.tsx
  src/pages/MyAccount/Setting.tsx
  src/pages/Register.tsx
  src/router/constants.ts
  src/router/router.tsx
  src/store/index.ts
  src/stories/NavigationBar.stories.tsx
  src/stories/example/Button.tsx
  src/stories/example/Header.tsx
  src/styles/common.ts
  src/utils/index.ts
Labels: feat

#43 mock 서버 카테고리 조회 api 구현
  fe/public/mockServiceWorker.js
  fe/src/api/constants.ts
  fe/src/api/index.ts
  fe/src/mocks/data/categories.ts
  fe/src/mocks/handlers.ts
  fe/tsconfig.json
Labels: feat

#44 유저 기능 추가 구현
  fe/src/api/constants.ts
  fe/src/api/fetcher.ts
  fe/src/api/index.ts
  fe/src/api/queries.ts
  fe/src/api/type.ts
  fe/src/assets/image/error.gif
  fe/src/components/Modal/AddressModal/AddressModal.tsx
  fe/src/components/Modal/AddressModal/Content/AddressIndicatorList.tsx
  fe/src/components/Modal/AddressModal/Content/AddressSearch.tsx
  fe/src/components/NameEditor.tsx
  fe/src/components/ProfileUploadButton.tsx
  fe/src/components/UserAccount.tsx
  fe/src/components/common/Guide.tsx
  fe/src/hooks/useIntersect.ts
  fe/src/main.tsx
  fe/src/mocks/data/address.ts
  fe/src/mocks/handlers.ts
  fe/src/mocks/mswSetup.ts
  fe/src/pages/Auth.tsx
  fe/src/pages/MyAccount/MyAccount.tsx
  fe/src/pages/MyAccount/Setting.tsx
  fe/src/pages/Register.tsx
  fe/src/store/index.ts
  fe/src/styles/common.ts
Labels: feat

#47 Toaster 컴포넌트 구현 및 useToast hook 생성
  fe/src/App.tsx
  fe/src/api/constants.ts
  fe/src/api/index.ts
  fe/src/api/queries.ts
  fe/src/assets/icon/error.svg
  fe/src/assets/icon/info.svg
  fe/src/assets/icon/success.svg
  fe/src/components/Modal/AddressModal/AddressModal.tsx
  fe/src/components/NameEditor.tsx
  fe/src/components/ProfileUploadButton.tsx
  fe/src/components/common/Toaster.tsx
  fe/src/hooks/useToast.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/Auth.tsx
  fe/src/store/UserProvider.tsx
  fe/src/store/index.ts
  fe/src/store/toaster.ts
  fe/src/styles/common.ts
Labels: feat

#52 카테고리 페이지
  fe/src/api/index.ts
  fe/src/api/queries.ts
  fe/src/api/type.ts
  fe/src/components/Category.tsx
  fe/src/mocks/data/categories.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/Home/Category.tsx
  fe/src/pages/Home/Home.tsx
Labels: feat

#54 fix: API reponse body 변경사항 반영
  fe/src/api/index.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/Auth.tsx
  fe/src/pages/Category.tsx
  fe/src/store/UserProvider.tsx
Labels: fix

#55 상품 등록 페이지 리팩토링
  fe/src/api/queries.ts
  fe/src/api/type.ts
  fe/src/components/ProductRegister/ProductRegisterAddress.tsx
  fe/src/components/ProductRegister/ProductRegisterCategory.tsx
  fe/src/components/ProductRegister/ProductRegisterContent.tsx
  fe/src/components/ProductRegister/constants.ts
  fe/src/components/ProductRegister/type.ts
  fe/src/pages/ProductRegister.tsx
Labels: refactor, fix

#56 유저 정보 반복 요청 수정 & 마지막 방문 동네 저장
  fe/src/api/queries.ts
  fe/src/pages/Auth.tsx
  fe/src/store/UserProvider.tsx
  fe/src/store/index.ts
Labels: feat, fix

#59 3주차 리뷰 적용 및 상품 등록 페이지 리팩토링
  fe/src/components/ProductRegister/ProductRegisterAddress.tsx
  fe/src/components/ProductRegister/ProductRegisterCategory.tsx
  fe/src/components/ProductRegister/ProductRegisterContent.tsx
  fe/src/components/ProductRegister/constants.ts
  fe/src/hooks/useAutoHeight.ts
  fe/src/pages/ProductRegister.tsx
Labels: refactor

#63 3주차 마스터피드백 & 리뷰어 코드 리뷰 적용
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api/constants.ts
  fe/src/api/fetcher.ts
  fe/src/api/index.ts
  fe/src/api/product/constants.ts
  fe/src/api/product/index.ts
  fe/src/api/product/queries.ts
  fe/src/api/user/constants.ts
  fe/src/api/user/index.ts
  fe/src/api/user/queries.ts
  fe/src/components/Modal/AddressModal/AddressModal.tsx
  fe/src/components/Modal/AddressModal/Content/AddressSearch.tsx
  fe/src/components/NameEditor.tsx
  fe/src/components/NavigationBar.tsx
  fe/src/components/ProductRegister/ProductRegisterAddress.tsx
  fe/src/components/ProductRegister/ProductRegisterCategory.tsx
  fe/src/components/ProfileUploadButton.tsx
  fe/src/components/common/Toaster.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/Auth.tsx
  fe/src/pages/Category.tsx
  fe/src/pages/MyAccount/Login.tsx
  fe/src/pages/MyAccount/MyAccount.tsx
  fe/src/pages/MyAccount/Setting.tsx
  fe/src/pages/ProductRegister.tsx
  fe/src/router/ProtectedRoutes.tsx
  fe/src/router/UserProvider.tsx
  fe/src/router/router.tsx
  fe/src/store/index.ts
  fe/src/styles/GlobalStyle.tsx
  fe/src/styles/common.ts
  fe/src/styles/constants.ts
  fe/yarn.lock
Labels: refactor

#64 ProductListItem 컴포넌트, 홈 화면 작업
  fe/src/components/ProductList/ProductListFAB.tsx
  fe/src/components/ProductList/ProductListHeader.tsx
  fe/src/components/ProductListItem.tsx
  fe/src/components/ProductRegister/ProductRegisterAddress.tsx
  fe/src/components/ProductRegister/ProductRegisterContent.tsx
  fe/src/components/ProductRegister/ProductRegisterPrice.tsx
  fe/src/components/ProductRegister/ProductRegisterTitle.tsx
  fe/src/components/ProductRegister/constants.ts
  fe/src/components/ProductStatus.tsx
  fe/src/components/common/Menu/Menu.tsx
  fe/src/components/common/Menu/MenuIndicator.tsx
  fe/src/components/common/Menu/type.ts
  fe/src/hooks/useMenuPosition.ts
  fe/src/pages/Home.tsx
  fe/src/pages/ProductList.tsx
  fe/src/router/router.tsx
  fe/src/store/constants.ts
  fe/src/store/index.ts
  fe/src/styles/constants.ts
  fe/src/utils/constants.ts
  fe/src/utils/index.ts
  fe/yarn.lock
Labels: ui

#68 상품 삭제 api 기능 구현
  fe/src/api/product/constants.ts
  fe/src/api/product/index.ts
  fe/src/api/product/queries.ts
  fe/src/components/ProductListItem.tsx
  fe/src/components/ProductMoreButton.tsx
  fe/src/hooks/useMenuPosition.ts
Labels: feat

#65 상품 상세 페이지 메인 영역
  fe/package-lock.json
  fe/package.json
  fe/src/api/product/constants.ts
  fe/src/api/product/index.ts
  fe/src/api/product/queries.ts
  fe/src/api/type.ts
  fe/src/api/user/index.ts
  fe/src/assets/icon/chevron-down.svg
  fe/src/components/Modal/AddressModal/AddressModal.tsx
  fe/src/components/Modal/AddressModal/Content/AddressIndicatorList.tsx
  fe/src/components/Modal/CategoryModal/CategoryModal.tsx
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/ModalHeader.tsx
  fe/src/components/Modal/ProductStatusModal/ProductStatusContent.tsx
  fe/src/components/Modal/ProductStatusModal/ProductStatusModal.tsx
  fe/src/components/NameEditor.tsx
  fe/src/components/NavigationBar.tsx
  fe/src/components/ProductDetail/Buttons.tsx
  fe/src/components/ProductDetail/ProductContents/ProductContents.tsx
  fe/src/components/ProductDetail/ProductContents/ProductInfo.tsx
  fe/src/components/ProductDetail/ProductContents/SellerInfo.tsx
  fe/src/components/ProductDetail/ProductImageList.tsx
  fe/src/components/ProductDetail/ProductStatus.tsx
  fe/src/components/ProductDetail/common.style.ts
  fe/src/components/ProductRegister/ProductRegisterAddress.tsx
  fe/src/components/ProfileUploadButton.tsx
  fe/src/components/TopBar.tsx
  fe/src/components/common/Menu/MenuIndicator.tsx
  fe/src/components/common/Toaster.tsx
  fe/src/hooks/useMenuPosition.ts
  fe/src/hooks/useScroll.ts
  fe/src/mocks/data/productDetail.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/MyAccount/Setting.tsx
  fe/src/pages/ProductDetail.tsx
  fe/src/pages/ProductRegister.tsx
  fe/src/router/constants.ts
  fe/src/router/router.tsx
  fe/src/store/index.ts
  fe/src/styles/common.ts
  fe/src/styles/designSystem.ts
  fe/src/utils/time.ts
  fe/yarn.lock
Labels: feat

#69 상품 상세 페이지 관심 상품 추가/삭제 기능, 상품 삭제 기능
  fe/package-lock.json
  fe/package.json
  fe/src/api/product/index.ts
  fe/src/api/product/queries.ts
  fe/src/api/user/constants.ts
  fe/src/api/user/index.ts
  fe/src/api/user/queries.ts
  fe/src/components/ProductDetail/Buttons.tsx
  fe/src/components/ProductDetail/Buttons/BackButton.tsx
  fe/src/components/ProductDetail/Buttons/ChatButton.tsx
  fe/src/components/ProductDetail/Buttons/LikeButton.tsx
  fe/src/components/ProductDetail/Buttons/MoreButton.tsx
  fe/src/components/ProductListItem.tsx
  fe/src/components/ProductMoreButton.tsx
  fe/src/components/ProfileUploadButton.tsx
  fe/src/mocks/handlers.ts
  fe/src/pages/Auth.tsx
  fe/src/pages/MyAccount/Setting.tsx
  fe/src/pages/ProductDetail.tsx
  fe/src/pages/ProductRegister.tsx
  fe/yarn.lock
Labels: feat

#71 관심 상품 페이지
  fe/src/api/type.ts
  fe/src/api/user/index.ts
  fe/src/api/user/queries.ts
  fe/src/components/Modal/CategoryModal/CategoryModal.tsx
  fe/src/components/Modal/CategoryModal/CategoryModalContent.tsx
  fe/src/components/ProductList/Products.tsx
  fe/src/components/ProductListItem.tsx
  fe/src/components/ProductRegister/ProductRegisterCategory.tsx
  fe/src/components/ProductRegister/constants.ts
  fe/src/components/ProductRegister/type.ts
  fe/src/components/common/TabButtons.tsx
  fe/src/pages/ProductList.tsx
  fe/src/pages/ProductRegister.tsx
  fe/src/pages/WishList.tsx
Labels: feat

#72 홈 화면 기능 구현
  fe/src/api/product/index.ts
  fe/src/api/product/queries.ts
  fe/src/api/type.ts
  fe/src/api/user/constants.ts
  fe/src/api/user/index.ts
  fe/src/api/user/queries.ts
  fe/src/components/Modal/AddressModal/Content/AddressSearch.tsx
  fe/src/components/Modal/ProductStatusModal/ProductStatusContent.tsx
  fe/src/components/ProductDetail/Buttons/MoreButton.tsx
  fe/src/components/ProductList/ProductListHeader.tsx
  fe/src/components/ProductListItem.tsx
  fe/src/components/ProductMoreButton.tsx
  fe/src/components/ProductRegister/ImageItem.tsx
  fe/src/components/ProductRegister/ProductRegisterCategory.tsx
  fe/src/components/ProductRegister/ProductRegisterImage.tsx
  fe/src/components/ProductStatus.tsx
  fe/src/components/common/TabButtons.tsx
  fe/src/hooks/useMenuPosition.ts
  fe/src/pages/ProductList.tsx
  fe/src/pages/ProductRegister.tsx
  fe/src/pages/SalesList.tsx
  fe/src/pages/WishList.tsx
  fe/src/router/UserProvider.tsx
  fe/src/store/constants.ts
  fe/src/store/index.ts
  fe/src/styles/common.ts
  fe/src/utils/constants.ts
  fe/src/utils/index.ts
  fe/src/utils/time.ts
Labels: feat

#73 4주차 작업 리팩토링
  fe/src/components/Modal/AddressModal/AddressModal.tsx
  fe/src/components/Modal/AddressModal/Content/AddressIndicatorList.tsx
  fe/src/components/Modal/AddressModal/Content/AddressSearch.tsx
  fe/src/components/ProductMoreButton.tsx
Labels: refactor

#74 Products 컴포넌트 개선, 기본 주소 설정
  fe/src/components/ProductList/ProductListHeader.tsx
  fe/src/components/ProductList/Products.tsx
  fe/src/pages/MyAccount/Setting.tsx
  fe/src/pages/ProductList.tsx
  fe/src/pages/SalesList.tsx
  fe/src/pages/WishList.tsx
  fe/src/router/UserProvider.tsx
  fe/src/store/constants.ts
  fe/src/store/index.ts
Labels: refactor

#79 4주차 리뷰 반영 리팩토링
  fe/src/api/user/queries.ts
  fe/src/components/Modal/AddressModal/Content/AddressSearch.tsx
  fe/src/components/ProductDetail/Buttons/ProductLikeButton.tsx
  fe/src/components/ProductMoreButton.tsx
  fe/src/components/ProductStatus.tsx
  fe/src/components/common/Menu/MenuIndicator.tsx
  fe/src/hooks/useIntersect.ts
  fe/src/hooks/useMenuPosition.ts
  fe/src/pages/MyAccount/Setting.tsx
  fe/src/pages/ProductDetail.tsx
  fe/src/pages/ProductList.tsx
  fe/src/pages/ProductRegister.tsx
  fe/src/pages/Register.tsx
  fe/src/pages/SalesList.tsx
  fe/src/pages/WishList.tsx
  fe/src/router/router.tsx
  fe/src/store/index.ts
  fe/src/styles/common.ts
Labels: refactor

#80 tanstack-query key 관리 방식 개선 및 Products 컴포넌트 적용, 기타 타입 개선, 마지막 방문 동네 설정(찐막)
  fe/package-lock.json
  fe/package.json
  fe/src/api/product/index.ts
  fe/src/api/product/queries.ts
  fe/src/api/queryKeys.ts
  fe/src/api/user/index.ts
  fe/src/api/user/queries.ts
  fe/src/components/Modal/ProductStatusModal/ProductStatusContent.tsx
  fe/src/components/ProductDetail/Buttons/ProductLikeButton.tsx
  fe/src/components/ProductList/Products.tsx
  fe/src/components/ProductListItem.tsx
  fe/src/components/ProductMoreButton.tsx
  fe/src/pages/Auth.tsx
  fe/src/pages/ProductDetail.tsx
  fe/src/pages/ProductList.tsx
  fe/src/pages/ProductRegister.tsx
  fe/src/pages/SalesList.tsx
  fe/src/pages/WishList.tsx
  fe/src/router/UserProvider.tsx
  fe/src/store/index.ts
  fe/yarn.lock
Labels: refactor

#82 채팅 상세 페이지 채팅바 ui 작업
  fe/src/assets/icon/send.svg
  fe/src/components/ChatBar.tsx
Labels: ui

#83 채팅 상세 페이지 UI
  fe/src/components/ChatDetail/ChatBar.tsx
  fe/src/components/ChatDetail/ChatBubble.tsx
  fe/src/components/ChatDetail/ChatMoreButton.tsx
  fe/src/components/ChatDetail/DailyChat.tsx
  fe/src/components/ChatDetail/ProductBanner.tsx
  fe/src/components/ChatList/ChatListItem.tsx
  fe/src/components/ProductDetail/Buttons/MoreButton.tsx
  fe/src/components/common/Buttons/BackButton.tsx
  fe/src/pages/ChatDetail.tsx
  fe/src/pages/ChatList.tsx
  fe/src/pages/ProductDetail.tsx
  fe/src/router/router.tsx
  fe/src/utils/index.ts
Labels: ui

#86 동네 검색 기능 & 동네 설정 모달 개선
  fe/src/api/product/constants.ts
  fe/src/api/product/index.ts
  fe/src/api/product/queries.ts
  fe/src/api/queryKeys.ts
  fe/src/components/Modal/AddressModal/AddressModal.tsx
  fe/src/components/Modal/AddressModal/AddressRemoveAlert.tsx
  fe/src/components/Modal/AddressModal/Buttons/index.tsx
  fe/src/components/Modal/AddressModal/Content/AddressIndicatorList.tsx
  fe/src/components/Modal/AddressModal/Content/AddressSearch.tsx
  fe/src/components/ProductDetail/ProductContents/ProductInfo.tsx
  fe/src/mocks/handlers.ts
Labels: feat, refactor

#87 백로그 처리(페이지 애니메이션 및 리팩토링)
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/ChatDetail/ChatMoreButton.tsx
  fe/src/components/Modal/AddressModal/Content/AddressIndicatorList.tsx
  fe/src/components/Modal/AddressModal/Content/AddressSearch.tsx
  fe/src/components/ProductDetail/Buttons/MoreButton.tsx
  fe/src/components/ProductDetail/ProductStatus.tsx
  fe/src/components/ProductList/ProductListHeader.tsx
  fe/src/components/ProductListItem.tsx
  fe/src/components/ProductMoreButton.tsx
  fe/src/components/ProductRegister/ProductRegisterAddress.tsx
  fe/src/components/ProductRegister/ProductRegisterContent.tsx
  fe/src/components/ProductStatus.tsx
  fe/src/components/common/Buttons/BackButton.tsx
  fe/src/hooks/useAnimation.ts
  fe/src/pages/ChatDetail.tsx
  fe/src/pages/ChatList.tsx
  fe/src/pages/ProductDetail.tsx
  fe/src/pages/ProductList.tsx
  fe/src/pages/ProductRegister.tsx
  fe/src/pages/SalesList.tsx
  fe/src/pages/WishList.tsx
  fe/src/router/GlobalStateProvider.tsx
  fe/src/store/index.ts
  fe/src/styles/animate.ts
  fe/src/utils/index.ts
  fe/yarn.lock
Labels: refactor

#90 refreshToken 만료일시로 초기 로그인 상태 판별
  fe/src/api/constants.ts
  fe/src/api/fetcher.ts
  fe/src/api/type.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/Auth.tsx
  fe/src/pages/MyAccount/Setting.tsx
  fe/src/store/index.ts
  fe/src/utils/index.ts
Labels: feat

#91 fix: 토큰 재발급 로직 버그 수정
  fe/src/api/constants.ts
  fe/src/api/fetcher.ts
Labels: fix
